### PR TITLE
fix: server_status returns instance_id

### LINKED ISSUE #73: Generate unique identifier for instance id and store it in database
The instance id should be generated when we run the daemon for the first time. 
instance_id should be stored in the database. 
We should fetch instance id from database if present, generate new one otherwise

### PR DESCRIPTION
**Pull request by Vovke**
resolves #73

### CODE REVIEW

File: src/database.rs [hunk 1]
```diff
@@ -230,6 +235,40 @@ impl Database {
...
+                                let server_info: ServerInfo =
+                                    serde_json::from_slice(&server_info_data).map_err(|e| {
+                                        DbError::DeserializationError(e.to_string())
+                                    })?;
+                                Ok(server_info.instance_id)
+                            } else {
+                                let mut generator = Generator::default();
+                                let new_instance_id = generator
+                                    .next()
+                                    .unwrap_or_else(|| "unknown-instance".to_string());
```
Comment (fluiderson) [inline src/database.rs:255]:
```suggestion
                                    .unwrap();
```
The default generator always returns `Some()`.

**Review by fluiderson — DISMISSED** [review]

File: src/database.rs (hunk 1 above)
Comment (Slesarew) [reply src/database.rs:255]: This could be changed to meaning error in case namegen decides to use some awkward unreliable rng backend in future and we forget it, but this fallback seems reasonable to me at least for now. Or at least expect-style panic would work to explain why we just unwrap here.

File: src/database.rs [hunk 2]
```diff
@@ -245,6 +284,12 @@ impl Database {
         Ok(Self { tx })
     }
 
+    pub async fn initialize_server_info(&self) -> Result<String, DbError> {
```
Comment (Slesarew) [inline src/database.rs:287]: why not just do it at db init? We do it every time, there is not much sense to do this in parallel, we do it only once, if this fails we should not be running this system anyway.

**Review by Slesarew — APPROVED** [review]

**Review by Slesarew — CHANGES_REQUESTED** [review]
wait, bump version!

**Comment by Vovke** [comment]
Resolves #76

**Comment by Vovke** [comment]
Resolves #75

**Comment by Vovke** [comment]
Resoves #59

**Review by Slesarew — APPROVED** [review]
